spectaql:
  logoFile: ./../assets/meemoo-logo_lockup-pos-rgb.svg
  faviconFile: ./../favicon.ico
  displayAllServers: true  

introspection:
  removeTrailingPeriodFromDescriptions: false
  url: http://org-api-qas-meemoo.private.cloud.meemoo.be/

info:
  description: > 
    Documentation for meemoo's Organization API V2.
    This API provides access to information about organizations and persons within the meemoo context, such as content partners, educational partners, address sites, contact information, account managers, or personnel of meemoo. 
    It is a [GraphQL API](https://graphql.org/) that is conform the [2021 specification](https://spec.graphql.org/October2021/). 
  version: 0.2.0
  title: meemoo Organization API V2
  contact:
    name: meemoo
    email: support@meemoo.be
    url: https://meemoo.be
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

  # A non-standard array of items to display in your Introduction Area
  x-introItems:
    - title: Authentication
      description: > 
        This API uses authentication via [JSON Web Tokens (JWT)](https://jwt.io/). You can request the JWT token as follows using your meemoo username and password.
        
        1. Request a token via [https://oas-qas.meemoo.be/token](https://oas-qas.meemoo.be/token) or [https://oas.meemoo.be/token](https://oas.meemoo.be/token).
           ``` bash
           curl -v -u '<username/email/...>:<password>' "https://oas-qas.meemoo.be/token?grant_type=client_credentials&expires_in=31536000"
           curl -v -u '<username/email/...>:<password>' "https://oas.meemoo.be/token?grant_type=client_credentials&expires_in=31536000" # for PRD
           ```
        2. Use the token in the authorization header (bearer) or as a URI parameter (jwauth):
           ``` bash
           curl -v https://services-qas.viaa.be/organisation_v2/?jwtauth="eyJ0eXAiOiJKV1......tbjz4-r4"
           curl -v https://services.viaa.be/organisation_v2/?jwtauth="eyJ0eXAiOiJKV1......tbjz4-r4" # for PRD
           ```

    - title: GET request 
      description: >
        Een GraphQL GET request contains the GraphQL query in the `query` query string.

        ```
        curl -v https://services-qas.viaa.be/organisation_v2?query=<graphql_query>
        curl -v https://services.viaa.be/organisation_v2?query=<graphql_query> # for PRD
        ```

    - title: POST request 
      description: |
        A GraphQL POST request expects a JSON-encoded payload, hence the `Content-Type: application/json` header must be included in the request.
        The request payload is structured as follows:

        ``` json
        {
          "query": "...",
          "operationName": "...",
          "variables": { "myVariable": "someValue", ... }
        }
        ```
    - title: Testing
      description: >
        The QAS environment API also serves the [GraphQL Playground](https://github.com/graphql/graphql-playground) where queries can be tested in an interactive way.
        You can open the playground by directing your webbroweser towards [https://services-qas.viaa.be/organisation_v2](https://services-qas.viaa.be/organisation_v2).
        Note that you need to be authenticated in order to access the playground.

    - title: Back to docs
      url: https://developer.meemoo.be
          
servers:
  - url: https://services.viaa.be/organisation_v2
    description: Production
    production: true
    headers:
      - name: Authorization
        example: Bearer <YOUR_TOKEN_HERE>
        comment: Your JWT token. Must be included in all API calls or supplied by `jwtauth` query parameter.

  - url: https://services-qas.viaa.be/organisation_v2
    description: QAS
    production: false
    headers:
      - name: Authorization
        example: Bearer <YOUR_TOKEN_HERE>
        comment: Your API token. Must be included in all API calls or supplied by `jwtauth` query parameter..
